version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: epay_postgres
    environment:
      POSTGRES_USER: itio_user
      POSTGRES_PASSWORD: Admin@95555
      POSTGRES_DB: itio_golang
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - epay_network

  golang:
    build:
      context: .  # Current directory, since Dockerfile and other files are here
      dockerfile: Dockerfile
    container_name: epay_golang
    environment:
      DB_HOST: postgres
      DB_USER: itio_user
      DB_PASSWORD: Admin@95555
      DB_NAME: itio_golang
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - epay_network

volumes:
  postgres_data:

networks:
  epay_network:
